# Generated by Django 4.2.7 on 2023-11-11 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blowfishfile',
            options={},
        ),
    ]
