# Generated by Django 4.2.7 on 2023-11-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypt', '0004_remove_blowfishmodel_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='blowfishmodel',
            name='filename',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='blowfishmodel',
            name='path',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='blowfishmodel',
            name='category',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
