# Generated by Django 4.2.7 on 2023-11-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypt', '0005_blowfishmodel_filename_blowfishmodel_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blowfishmodel',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
