# Generated by Django 4.2.7 on 2023-11-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypt', '0006_blowfishmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blowfishmodel',
            name='efile',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
