# Generated by Django 4.2.7 on 2023-11-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypt', '0007_blowfishmodel_efile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blowfishmodel',
            name='efile',
            field=models.FileField(blank=True, null=True, upload_to='encrypted/'),
        ),
    ]
