# Generated by Django 4.2.7 on 2023-11-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypt', '0008_alter_blowfishmodel_efile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blowfishmodel',
            name='epath',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
