# Generated by Django 4.2.7 on 2023-11-16 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypt', '0009_blowfishmodel_epath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blowfishmodel',
            old_name='epath',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='blowfishmodel',
            old_name='path',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='blowfishmodel',
            name='efile',
        ),
    ]
